"""add_trading_recipes_table

Revision ID: 137261e2e3fa
Revises: e7f1a4b5c6d8
Create Date: 2026-02-15 13:47:41.469748
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '137261e2e3fa'
down_revision: Union[str, None] = 'e7f1a4b5c6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_recipes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('signal_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('custom_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stock_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_recipes_user_id'), 'trading_recipes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_recipes_user_id'), table_name='trading_recipes')
    op.drop_table('trading_recipes')
    # ### end Alembic commands ###
